/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package types;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LoggedIn extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5886723773190925177L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LoggedIn\",\"namespace\":\"types\",\"fields\":[{\"name\":\"customer_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"customer_type\",\"type\":[\"null\",\"string\"]},{\"name\":\"customer_address\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"AddressLine\",\"type\":[\"null\",\"string\"]},{\"name\":\"City\",\"type\":[\"null\",\"string\"]},{\"name\":\"State\",\"type\":[\"null\",\"string\"]},{\"name\":\"PinCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"ContactNumber\",\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"card_no\",\"type\":[\"null\",\"long\"]},{\"name\":\"txn_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"txn_amount\",\"type\":[\"null\",\"double\"]},{\"name\":\"merchant_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"merchant_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"merchant_address\",\"type\":[\"null\",\"Address\"]},{\"name\":\"is_offer_eligible\",\"type\":[\"null\",\"boolean\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence customer_id;
  @Deprecated public java.lang.CharSequence customer_type;
  @Deprecated public types.Address customer_address;
  @Deprecated public java.lang.Long card_no;
  @Deprecated public java.lang.CharSequence txn_id;
  @Deprecated public java.lang.Double txn_amount;
  @Deprecated public java.lang.CharSequence merchant_id;
  @Deprecated public java.lang.CharSequence merchant_name;
  @Deprecated public types.Address merchant_address;
  @Deprecated public java.lang.Boolean is_offer_eligible;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LoggedIn() {}

  /**
   * All-args constructor.
   * @param customer_id The new value for customer_id
   * @param customer_type The new value for customer_type
   * @param customer_address The new value for customer_address
   * @param card_no The new value for card_no
   * @param txn_id The new value for txn_id
   * @param txn_amount The new value for txn_amount
   * @param merchant_id The new value for merchant_id
   * @param merchant_name The new value for merchant_name
   * @param merchant_address The new value for merchant_address
   * @param is_offer_eligible The new value for is_offer_eligible
   */
  public LoggedIn(java.lang.CharSequence customer_id, java.lang.CharSequence customer_type, types.Address customer_address, java.lang.Long card_no, java.lang.CharSequence txn_id, java.lang.Double txn_amount, java.lang.CharSequence merchant_id, java.lang.CharSequence merchant_name, types.Address merchant_address, java.lang.Boolean is_offer_eligible) {
    this.customer_id = customer_id;
    this.customer_type = customer_type;
    this.customer_address = customer_address;
    this.card_no = card_no;
    this.txn_id = txn_id;
    this.txn_amount = txn_amount;
    this.merchant_id = merchant_id;
    this.merchant_name = merchant_name;
    this.merchant_address = merchant_address;
    this.is_offer_eligible = is_offer_eligible;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customer_id;
    case 1: return customer_type;
    case 2: return customer_address;
    case 3: return card_no;
    case 4: return txn_id;
    case 5: return txn_amount;
    case 6: return merchant_id;
    case 7: return merchant_name;
    case 8: return merchant_address;
    case 9: return is_offer_eligible;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customer_id = (java.lang.CharSequence)value$; break;
    case 1: customer_type = (java.lang.CharSequence)value$; break;
    case 2: customer_address = (types.Address)value$; break;
    case 3: card_no = (java.lang.Long)value$; break;
    case 4: txn_id = (java.lang.CharSequence)value$; break;
    case 5: txn_amount = (java.lang.Double)value$; break;
    case 6: merchant_id = (java.lang.CharSequence)value$; break;
    case 7: merchant_name = (java.lang.CharSequence)value$; break;
    case 8: merchant_address = (types.Address)value$; break;
    case 9: is_offer_eligible = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customer_id' field.
   * @return The value of the 'customer_id' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customer_id;
  }

  /**
   * Sets the value of the 'customer_id' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customer_id = value;
  }

  /**
   * Gets the value of the 'customer_type' field.
   * @return The value of the 'customer_type' field.
   */
  public java.lang.CharSequence getCustomerType() {
    return customer_type;
  }

  /**
   * Sets the value of the 'customer_type' field.
   * @param value the value to set.
   */
  public void setCustomerType(java.lang.CharSequence value) {
    this.customer_type = value;
  }

  /**
   * Gets the value of the 'customer_address' field.
   * @return The value of the 'customer_address' field.
   */
  public types.Address getCustomerAddress() {
    return customer_address;
  }

  /**
   * Sets the value of the 'customer_address' field.
   * @param value the value to set.
   */
  public void setCustomerAddress(types.Address value) {
    this.customer_address = value;
  }

  /**
   * Gets the value of the 'card_no' field.
   * @return The value of the 'card_no' field.
   */
  public java.lang.Long getCardNo() {
    return card_no;
  }

  /**
   * Sets the value of the 'card_no' field.
   * @param value the value to set.
   */
  public void setCardNo(java.lang.Long value) {
    this.card_no = value;
  }

  /**
   * Gets the value of the 'txn_id' field.
   * @return The value of the 'txn_id' field.
   */
  public java.lang.CharSequence getTxnId() {
    return txn_id;
  }

  /**
   * Sets the value of the 'txn_id' field.
   * @param value the value to set.
   */
  public void setTxnId(java.lang.CharSequence value) {
    this.txn_id = value;
  }

  /**
   * Gets the value of the 'txn_amount' field.
   * @return The value of the 'txn_amount' field.
   */
  public java.lang.Double getTxnAmount() {
    return txn_amount;
  }

  /**
   * Sets the value of the 'txn_amount' field.
   * @param value the value to set.
   */
  public void setTxnAmount(java.lang.Double value) {
    this.txn_amount = value;
  }

  /**
   * Gets the value of the 'merchant_id' field.
   * @return The value of the 'merchant_id' field.
   */
  public java.lang.CharSequence getMerchantId() {
    return merchant_id;
  }

  /**
   * Sets the value of the 'merchant_id' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.CharSequence value) {
    this.merchant_id = value;
  }

  /**
   * Gets the value of the 'merchant_name' field.
   * @return The value of the 'merchant_name' field.
   */
  public java.lang.CharSequence getMerchantName() {
    return merchant_name;
  }

  /**
   * Sets the value of the 'merchant_name' field.
   * @param value the value to set.
   */
  public void setMerchantName(java.lang.CharSequence value) {
    this.merchant_name = value;
  }

  /**
   * Gets the value of the 'merchant_address' field.
   * @return The value of the 'merchant_address' field.
   */
  public types.Address getMerchantAddress() {
    return merchant_address;
  }

  /**
   * Sets the value of the 'merchant_address' field.
   * @param value the value to set.
   */
  public void setMerchantAddress(types.Address value) {
    this.merchant_address = value;
  }

  /**
   * Gets the value of the 'is_offer_eligible' field.
   * @return The value of the 'is_offer_eligible' field.
   */
  public java.lang.Boolean getIsOfferEligible() {
    return is_offer_eligible;
  }

  /**
   * Sets the value of the 'is_offer_eligible' field.
   * @param value the value to set.
   */
  public void setIsOfferEligible(java.lang.Boolean value) {
    this.is_offer_eligible = value;
  }

  /**
   * Creates a new LoggedIn RecordBuilder.
   * @return A new LoggedIn RecordBuilder
   */
  public static types.LoggedIn.Builder newBuilder() {
    return new types.LoggedIn.Builder();
  }

  /**
   * Creates a new LoggedIn RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LoggedIn RecordBuilder
   */
  public static types.LoggedIn.Builder newBuilder(types.LoggedIn.Builder other) {
    return new types.LoggedIn.Builder(other);
  }

  /**
   * Creates a new LoggedIn RecordBuilder by copying an existing LoggedIn instance.
   * @param other The existing instance to copy.
   * @return A new LoggedIn RecordBuilder
   */
  public static types.LoggedIn.Builder newBuilder(types.LoggedIn other) {
    return new types.LoggedIn.Builder(other);
  }

  /**
   * RecordBuilder for LoggedIn instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LoggedIn>
    implements org.apache.avro.data.RecordBuilder<LoggedIn> {

    private java.lang.CharSequence customer_id;
    private java.lang.CharSequence customer_type;
    private types.Address customer_address;
    private types.Address.Builder customer_addressBuilder;
    private java.lang.Long card_no;
    private java.lang.CharSequence txn_id;
    private java.lang.Double txn_amount;
    private java.lang.CharSequence merchant_id;
    private java.lang.CharSequence merchant_name;
    private types.Address merchant_address;
    private types.Address.Builder merchant_addressBuilder;
    private java.lang.Boolean is_offer_eligible;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(types.LoggedIn.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[0].schema(), other.customer_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customer_type)) {
        this.customer_type = data().deepCopy(fields()[1].schema(), other.customer_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[2].schema(), other.customer_address);
        fieldSetFlags()[2] = true;
      }
      if (other.hasCustomerAddressBuilder()) {
        this.customer_addressBuilder = types.Address.newBuilder(other.getCustomerAddressBuilder());
      }
      if (isValidValue(fields()[3], other.card_no)) {
        this.card_no = data().deepCopy(fields()[3].schema(), other.card_no);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.txn_id)) {
        this.txn_id = data().deepCopy(fields()[4].schema(), other.txn_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.txn_amount)) {
        this.txn_amount = data().deepCopy(fields()[5].schema(), other.txn_amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[6].schema(), other.merchant_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.merchant_name)) {
        this.merchant_name = data().deepCopy(fields()[7].schema(), other.merchant_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.merchant_address)) {
        this.merchant_address = data().deepCopy(fields()[8].schema(), other.merchant_address);
        fieldSetFlags()[8] = true;
      }
      if (other.hasMerchantAddressBuilder()) {
        this.merchant_addressBuilder = types.Address.newBuilder(other.getMerchantAddressBuilder());
      }
      if (isValidValue(fields()[9], other.is_offer_eligible)) {
        this.is_offer_eligible = data().deepCopy(fields()[9].schema(), other.is_offer_eligible);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LoggedIn instance
     * @param other The existing instance to copy.
     */
    private Builder(types.LoggedIn other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[0].schema(), other.customer_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customer_type)) {
        this.customer_type = data().deepCopy(fields()[1].schema(), other.customer_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[2].schema(), other.customer_address);
        fieldSetFlags()[2] = true;
      }
      this.customer_addressBuilder = null;
      if (isValidValue(fields()[3], other.card_no)) {
        this.card_no = data().deepCopy(fields()[3].schema(), other.card_no);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.txn_id)) {
        this.txn_id = data().deepCopy(fields()[4].schema(), other.txn_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.txn_amount)) {
        this.txn_amount = data().deepCopy(fields()[5].schema(), other.txn_amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[6].schema(), other.merchant_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.merchant_name)) {
        this.merchant_name = data().deepCopy(fields()[7].schema(), other.merchant_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.merchant_address)) {
        this.merchant_address = data().deepCopy(fields()[8].schema(), other.merchant_address);
        fieldSetFlags()[8] = true;
      }
      this.merchant_addressBuilder = null;
      if (isValidValue(fields()[9], other.is_offer_eligible)) {
        this.is_offer_eligible = data().deepCopy(fields()[9].schema(), other.is_offer_eligible);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'customer_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customer_id;
    }

    /**
      * Sets the value of the 'customer_id' field.
      * @param value The value of 'customer_id'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.customer_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_id' field has been set.
      * @return True if the 'customer_id' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customer_id' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearCustomerId() {
      customer_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerType() {
      return customer_type;
    }

    /**
      * Sets the value of the 'customer_type' field.
      * @param value The value of 'customer_type'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setCustomerType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customer_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_type' field has been set.
      * @return True if the 'customer_type' field has been set, false otherwise.
      */
    public boolean hasCustomerType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customer_type' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearCustomerType() {
      customer_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_address' field.
      * @return The value.
      */
    public types.Address getCustomerAddress() {
      return customer_address;
    }

    /**
      * Sets the value of the 'customer_address' field.
      * @param value The value of 'customer_address'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setCustomerAddress(types.Address value) {
      validate(fields()[2], value);
      this.customer_addressBuilder = null;
      this.customer_address = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_address' field has been set.
      * @return True if the 'customer_address' field has been set, false otherwise.
      */
    public boolean hasCustomerAddress() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'customer_address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public types.Address.Builder getCustomerAddressBuilder() {
      if (customer_addressBuilder == null) {
        if (hasCustomerAddress()) {
          setCustomerAddressBuilder(types.Address.newBuilder(customer_address));
        } else {
          setCustomerAddressBuilder(types.Address.newBuilder());
        }
      }
      return customer_addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'customer_address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public types.LoggedIn.Builder setCustomerAddressBuilder(types.Address.Builder value) {
      clearCustomerAddress();
      customer_addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'customer_address' field has an active Builder instance
     * @return True if the 'customer_address' field has an active Builder instance
     */
    public boolean hasCustomerAddressBuilder() {
      return customer_addressBuilder != null;
    }

    /**
      * Clears the value of the 'customer_address' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearCustomerAddress() {
      customer_address = null;
      customer_addressBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'card_no' field.
      * @return The value.
      */
    public java.lang.Long getCardNo() {
      return card_no;
    }

    /**
      * Sets the value of the 'card_no' field.
      * @param value The value of 'card_no'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setCardNo(java.lang.Long value) {
      validate(fields()[3], value);
      this.card_no = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'card_no' field has been set.
      * @return True if the 'card_no' field has been set, false otherwise.
      */
    public boolean hasCardNo() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'card_no' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearCardNo() {
      card_no = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'txn_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getTxnId() {
      return txn_id;
    }

    /**
      * Sets the value of the 'txn_id' field.
      * @param value The value of 'txn_id'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setTxnId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.txn_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'txn_id' field has been set.
      * @return True if the 'txn_id' field has been set, false otherwise.
      */
    public boolean hasTxnId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'txn_id' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearTxnId() {
      txn_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'txn_amount' field.
      * @return The value.
      */
    public java.lang.Double getTxnAmount() {
      return txn_amount;
    }

    /**
      * Sets the value of the 'txn_amount' field.
      * @param value The value of 'txn_amount'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setTxnAmount(java.lang.Double value) {
      validate(fields()[5], value);
      this.txn_amount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'txn_amount' field has been set.
      * @return True if the 'txn_amount' field has been set, false otherwise.
      */
    public boolean hasTxnAmount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'txn_amount' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearTxnAmount() {
      txn_amount = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantId() {
      return merchant_id;
    }

    /**
      * Sets the value of the 'merchant_id' field.
      * @param value The value of 'merchant_id'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setMerchantId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.merchant_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_id' field has been set.
      * @return True if the 'merchant_id' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'merchant_id' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearMerchantId() {
      merchant_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantName() {
      return merchant_name;
    }

    /**
      * Sets the value of the 'merchant_name' field.
      * @param value The value of 'merchant_name'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setMerchantName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.merchant_name = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_name' field has been set.
      * @return True if the 'merchant_name' field has been set, false otherwise.
      */
    public boolean hasMerchantName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'merchant_name' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearMerchantName() {
      merchant_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_address' field.
      * @return The value.
      */
    public types.Address getMerchantAddress() {
      return merchant_address;
    }

    /**
      * Sets the value of the 'merchant_address' field.
      * @param value The value of 'merchant_address'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setMerchantAddress(types.Address value) {
      validate(fields()[8], value);
      this.merchant_addressBuilder = null;
      this.merchant_address = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_address' field has been set.
      * @return True if the 'merchant_address' field has been set, false otherwise.
      */
    public boolean hasMerchantAddress() {
      return fieldSetFlags()[8];
    }

    /**
     * Gets the Builder instance for the 'merchant_address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public types.Address.Builder getMerchantAddressBuilder() {
      if (merchant_addressBuilder == null) {
        if (hasMerchantAddress()) {
          setMerchantAddressBuilder(types.Address.newBuilder(merchant_address));
        } else {
          setMerchantAddressBuilder(types.Address.newBuilder());
        }
      }
      return merchant_addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'merchant_address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public types.LoggedIn.Builder setMerchantAddressBuilder(types.Address.Builder value) {
      clearMerchantAddress();
      merchant_addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'merchant_address' field has an active Builder instance
     * @return True if the 'merchant_address' field has an active Builder instance
     */
    public boolean hasMerchantAddressBuilder() {
      return merchant_addressBuilder != null;
    }

    /**
      * Clears the value of the 'merchant_address' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearMerchantAddress() {
      merchant_address = null;
      merchant_addressBuilder = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_offer_eligible' field.
      * @return The value.
      */
    public java.lang.Boolean getIsOfferEligible() {
      return is_offer_eligible;
    }

    /**
      * Sets the value of the 'is_offer_eligible' field.
      * @param value The value of 'is_offer_eligible'.
      * @return This builder.
      */
    public types.LoggedIn.Builder setIsOfferEligible(java.lang.Boolean value) {
      validate(fields()[9], value);
      this.is_offer_eligible = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'is_offer_eligible' field has been set.
      * @return True if the 'is_offer_eligible' field has been set, false otherwise.
      */
    public boolean hasIsOfferEligible() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'is_offer_eligible' field.
      * @return This builder.
      */
    public types.LoggedIn.Builder clearIsOfferEligible() {
      is_offer_eligible = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public LoggedIn build() {
      try {
        LoggedIn record = new LoggedIn();
        record.customer_id = fieldSetFlags()[0] ? this.customer_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customer_type = fieldSetFlags()[1] ? this.customer_type : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (customer_addressBuilder != null) {
          record.customer_address = this.customer_addressBuilder.build();
        } else {
          record.customer_address = fieldSetFlags()[2] ? this.customer_address : (types.Address) defaultValue(fields()[2]);
        }
        record.card_no = fieldSetFlags()[3] ? this.card_no : (java.lang.Long) defaultValue(fields()[3]);
        record.txn_id = fieldSetFlags()[4] ? this.txn_id : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.txn_amount = fieldSetFlags()[5] ? this.txn_amount : (java.lang.Double) defaultValue(fields()[5]);
        record.merchant_id = fieldSetFlags()[6] ? this.merchant_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.merchant_name = fieldSetFlags()[7] ? this.merchant_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        if (merchant_addressBuilder != null) {
          record.merchant_address = this.merchant_addressBuilder.build();
        } else {
          record.merchant_address = fieldSetFlags()[8] ? this.merchant_address : (types.Address) defaultValue(fields()[8]);
        }
        record.is_offer_eligible = fieldSetFlags()[9] ? this.is_offer_eligible : (java.lang.Boolean) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
